---
- name: Init Azure
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - settings.yml
  tasks:
    - name: Getting servers
      shell: "azure vm list -s {{ azure.subscription_id }}"
      register: servers
      changed_when: false
      always_run: yes
    - name: Create Server
      shell: "azure vm create {{ azure.name }} {{ azure.image }} -c -g {{ admin_user }} -e {{ azure.ssh_port }} -u {{ azure.blob_url }}/{{ azure.name }}.vhd -t {{ azure.ssh_pem }} -P -z {{ azure.size }} -l '{{ azure.region }}' -s {{ azure.subscription_id }}"
      when: servers.stdout.find("{{ azure.name }}") == -1
    - name: Getting endpoints
      shell: "azure vm endpoint list {{ azure.name }} -s {{ azure.subscription_id }}"
      register: endpoints
      changed_when: false
      always_run: yes
    - name: Set endpoints
      shell: "azure vm endpoint create {{ azure.name }} {{ item }} -s {{ azure.subscription_id }}"
      when: endpoints.stdout.find("{{ item }}") == -1
      with_items: chef.server.ports_azure
